### ISSUE TITLE
Mobile View Layout Optimization for "blog-home" Page

### ISSUE THREAD

**Issue by rainfall-serenity** [open17/vitepress-theme-open17#6]
### Description:
The current "blog-home" page layout on mobile and smaller screens places the avatar, tags, and custom section at the top. This arrangement requires excessive scrolling to reach the actual content, which impacts user experience.

### Steps to Reproduce:
Open the "blog-home" page on a mobile device or in a mobile view emulator.
Observe the placement of avatars, tags, and custom sections.
Note the excessive scrolling required to view the main content.

### Expected Behavior:
The layout should be optimized to improve content accessibility and reduce scrolling. Consider reorganizing elements to prioritize content visibility.

### Suggested Solution:
Refer to the optimization approach used in the [sugar-blog repository](https://github.com/ATQQ/sugar-blog) for inspiration on how to better structure the mobile view layout.

### Additional Notes:
The current theme is well-appreciated. Keep up the good work!

**Comment by open17** [comment]
Thanks for raising this issuse. Your feedback is extremely valuable to me.
